<?php

return $language = array(
	"delete_img" => __('Delete Image', 'mp-restaurant-menu'),
	"delete" => __('Delete', 'mp-restaurant-menu'),
	"insert_media" => __('Insert a media', 'mp-restaurant-menu'),
	"insert" => __('Insert', 'mp-restaurant-menu'),
	"choose_image" => __('Choose an image', 'mp-restaurant-menu'),
	"use_image" => __('Select', 'mp-restaurant-menu'),
	"shortcode_title" => __('Insert Restaurant Menu Shortcode', 'mp-restaurant-menu'),
	"cancel" => __('Cancel', 'mp-restaurant-menu'),
	"choose" => __('Choose', 'mp-restaurant-menu'),
	//'post_id' => isset($post->ID) ? $post->ID : null,
	//'edd_version' => EDD_VERSION,
	'add_new_download' => __('Add New Download', 'easy-digital-downloads'),
	'use_this_file' => __('Use This File', 'easy-digital-downloads'),
	'quick_edit_warning' => __('Sorry, not available for variable priced products.', 'easy-digital-downloads'),
	'delete_payment' => __('Are you sure you wish to delete this payment?', 'easy-digital-downloads'),
	'delete_payment_note' => __('Are you sure you wish to delete this note?', 'easy-digital-downloads'),
	'delete_tax_rate' => __('Are you sure you wish to delete this tax rate?', 'easy-digital-downloads'),
	'revoke_api_key' => __('Are you sure you wish to revoke this API key?', 'easy-digital-downloads'),
	'regenerate_api_key' => __('Are you sure you wish to regenerate this API key?', 'easy-digital-downloads'),
	'resend_receipt' => __('Are you sure you wish to resend the purchase receipt?', 'easy-digital-downloads'),
	'copy_download_link_text' => __('Copy these links to your clipboard and give them to your customer', 'easy-digital-downloads'),
	//'delete_payment_download' => sprintf(__('Are you sure you wish to delete this %s?', 'easy-digital-downloads'), edd_get_label_singular()),
	'one_price_min' => __('You must have at least one price', 'easy-digital-downloads'),
	'one_field_min' => __('You must have at least one field', 'easy-digital-downloads'),
	'one_download_min' => __('Payments must contain at least one item', 'easy-digital-downloads'),
	//'one_option' => sprintf(__('Choose a %s', 'easy-digital-downloads'), edd_get_label_singular()),
	//'one_or_more_option' => sprintf(__('Choose one or more %s', 'easy-digital-downloads'), edd_get_label_plural()),
	'numeric_item_price' => __('Item price must be numeric', 'easy-digital-downloads'),
	'numeric_quantity' => __('Quantity must be numeric', 'easy-digital-downloads'),
	//'currency' => edd_get_currency(),
	//'currency_sign' => edd_currency_filter(''),
	//'currency_pos' => edd_get_option('currency_position', 'before'),
	//'currency_decimals' => edd_currency_decimal_filter(),
	'new_media_ui' => apply_filters('mprm_use_35_media_ui', 1),
	'remove_text' => __('Remove', 'easy-digital-downloads'),
	//'type_to_search' => sprintf(__('Type to search %s', 'easy-digital-downloads'), edd_get_label_plural()),
	//'quantities_enabled' => edd_item_quantities_enabled(),
	'batch_export_no_class' => __('You must choose a method.', 'easy-digital-downloads'),
	'batch_export_no_reqs' => __('Required fields not completed.', 'easy-digital-downloads'),
	'reset_stats_warn' => __('Are you sure you want to reset your store? This process is <strong><em>not reversible</em></strong>. Please be sure you have a recent backup.', 'easy-digital-downloads'),

);
